name: 'Get Changed Directories'
description: 'Get changed directories within a specified directory'
inputs:
  base-directory:
    description: 'Base directory to check for changes'
    required: true
  exclude-dirs:
    description: 'Comma-separated list of directories to exclude'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
outputs:
  changed-dirs:
    description: 'JSON array of changed directories'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm ci

    - name: Build TypeScript
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm run build

    - name: Run the action
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      working-directory: ${{ github.workspace }}
      run: |
        node ${{ github.action_path }}/dist/index.js \
          --base-directory "${{ inputs.base-directory }}" \
          --exclude-dirs "${{ inputs.exclude-dirs }}" 