name: 'Get Changed Directories'
description: 'Get changed directories within a specified directory'
inputs:
  base-directory:
    description: 'Base directory to check for changes'
    required: true
  exclude-dirs:
    description: 'Comma-separated list of directories to exclude'
    required: false
    default: ''
outputs:
  changed-dirs:
    description: 'JSON array of changed directories'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build TypeScript
      shell: bash
      run: npm run build

    - name: Run the action
      shell: bash
      run: |
        node dist/index.js \
          --base-directory "${{ inputs.base-directory }}" \
          --exclude-dirs "${{ inputs.exclude-dirs }}" 