name: 'Get Changed Directories'
description: 'Get changed directories within a specified directory'
inputs:
  base-directory:
    description: 'Base directory to check for changes'
    required: true
  exclude-dirs:
    description: 'Comma-separated list of directories to exclude'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
outputs:
  changed-dirs:
    description: 'JSON array of changed directories'
    value: ${{ steps.get-changed-dirs.outputs.changed-dirs }}
runs:
  using: 'node20'
  main: 'dist/index.js'