name: 'Get Changed Directories'
description: 'Get changed directories within a specified directory'
inputs:
  base-directory:
    description: 'Base directory to check for changes'
    required: true
  exclude-dirs:
    description: 'Comma-separated list of directories to exclude'
    required: false
    default: ''
outputs:
  changed-dirs:
    description: 'JSON array of changed directories'
runs:
  using: 'node20'
  main: 'dist/index.js'
  pre: 'npm ci && npm run build' 